# This runs a simple toast destriper mapmaker on a TOAST data object.
# Author : Henry Nachman
# Date : 25 September 2026

import matplotlib.pyplot as plt
import numpy as np
import os
import healpy as hp
import toast
from toast.observation import default_values as defaults
import astropy.units as u

from toast import Data

def plot_maps(
    root,
    range_I=(-0.01, 0.01),
    range_Q=(-0.0002, 0.0002),
    range_U=(-0.0002, 0.0002),
    max_hits=1000,
    truth=None,
):
    """
    Plot the maps generated by the TOAST mapmaker.
    
    Parameters
    ----------
    root : str
        The root of the files from the TOAST mapmaker.
    range_I : tuple, optional
        The range of values to display for the I map. Default is (-0.01, 0.01).
    range_Q : tuple, optional
        The range of values to display for the Q map. Default is (-0.0002, 0.0002).
    range_U : tuple, optional
        The range of values to display for the U map. Default is (-0.0002, 0.0002).
    max_hits : int, optional
        The maximum number of hits to display in the hits map. Default is 1000.
    truth : str, optional
        The path to the truth map file for comparison. If provided, the residual maps will be plotted. Default is None.
    
    
    """
    cmap = "viridis"
    gnomres = 8.0
    gnomrot = (199.5, 8.3)
    xsize = 800
    
    hits_file = os.path.join(root, "mapmaker_hits.fits")
    rcond_file = os.path.join(root, "mapmaker_rcond.fits")
    binmap_file = os.path.join(root, "mapmaker_binmap.fits")
    map_file = os.path.join(root, "mapmaker_map.fits")

    # Load hits
    hits = hp.read_map(hits_file, field=None, nest=True)
    goodhits = hits > 0
    badhits = np.logical_not(goodhits)

    # Load rcond
    rcond = hp.read_map(rcond_file, field=None, nest=True)
    rcond[badhits] = hp.UNSEEN

    # Maps
    maps = hp.read_map(map_file, field=None, nest=True)
    binmaps = hp.read_map(binmap_file, field=None, nest=True)
    resid = None
    resid_bin = None
    if truth is not None:
        truth_maps = hp.read_map(truth, field=None, nest=True)
        resid = list()
        resid_bin = list()
        for i in range(3):
            resid.append(np.array(maps[i]) - truth_maps[i])
            resid_bin.append(np.array(binmaps[i]) - truth_maps[i])
    for i in range(3):
        maps[i][badhits] = hp.UNSEEN
        binmaps[i][badhits] = hp.UNSEEN
        if truth is not None:
            truth_maps[i][badhits] = hp.UNSEEN
            resid[i][badhits] = hp.UNSEEN
            resid_bin[i][badhits] = hp.UNSEEN

    # Plot hits and rcond
    fig = plt.figure(dpi=100, figsize=(18, 12))
    hp.gnomview(
        map=hits,
        fig=fig.number,
        sub=(1, 2, 1),
        rot=gnomrot,
        xsize=xsize,
        reso=gnomres,
        nest=True,
        cmap=cmap,
        min=0,
        max=max_hits,
        title="Hits",
    )
    hp.gnomview(
        map=rcond,
        fig=fig.number,
        sub=(1, 2, 2),
        rot=gnomrot,
        xsize=xsize,
        reso=gnomres,
        nest=True,
        cmap=cmap,
        min=0,
        max=0.5,
        title="Inverse Condition Number",
    )
    plt.show()
    plt.close()

    # Plot maps
    
    plot_cols = 2
    if truth is not None:
        plot_cols = 4
    plot_rows = 3
    fig = plt.figure(dpi=100, figsize=(18, 18))
    counter = 1
    for row, (stokes, rng) in enumerate([("I", range_I), ("Q", range_Q), ("U", range_U)]):
        for mps, res, name in [(maps, resid, "Destriped"), (binmaps, resid_bin, "Binned")]:
            hp.gnomview(
                map=mps[row],
                fig=fig.number,
                sub=(plot_rows, plot_cols, counter),
                rot=gnomrot,
                xsize=xsize,
                reso=gnomres,
                nest=True,
                cmap=cmap,
                min=rng[0],
                max=rng[1],
                title=f"{name} Stokes {stokes}",
            )
            counter += 1
            if truth is not None:
                hp.gnomview(
                    map=res[row],
                    fig=fig.number,
                    sub=(plot_rows, plot_cols, counter),
                    rot=gnomrot,
                    xsize=xsize,
                    reso=gnomres,
                    nest=True,
                    cmap=cmap,
                    min=rng[0],
                    max=rng[1],
                    title=f"{name} Stokes {stokes} Minus Input",
                )
                counter += 1
    plt.savefig(os.path.join(root, f"filterbinned_maps.png"), dpi=100)
    plt.show()
    plt.close()

def toast_mapmaker(data = None, data_volume : str = "", out_dir : str = ""):
    """
    Perform a simple generalized destriper mapmaking operation on a set
    of TOAST data.

    Parameters
    ----------
    data : toast.Data
        The TOAST data object containing the observations and pointing information.
    data_volume : str
        The path to the input data volume (HDF5 file) containing the TOAST data. 
        Can be specified in lieu of a data object.
    out_dir : str
        The directory where the output maps and related files will be saved.
    """

    # Load the data from the input file
    if data is None:
        # No data object has been provided, so we need to load it from the specified data volume.
        if os.path.exists(data_volume):
            data = toast.Data()
            load_data = toast.ops.LoadHDF5(volume=data_volume)
            load_data.apply(data)
        else:
            raise FileNotFoundError(f"The specified data volume '{data_volume}' does not exist. Please provide a valid path to the TOAST data volume or a pre-loaded data object.")
    else:
        # A data object has been provided, so we will use it directly.
        if not isinstance(data, toast.Data):
            raise TypeError("The provided 'data' argument must be an instance of 'toast.Data'.")

    # Filtering
    filter = toast.ops.CommonModeFilter(
        redistribute=False,
        regress=True,
    )

    filter.apply(data)

    # Estimate noise
    estim = toast.ops.NoiseEstim(
        out_model="noise_estimate",
        lagmax=100,
        nbin_psd=32,
        nsum=1,
    )
    estim.apply(data)

    # Compute a 1/f fit to this
    noise_fitter = toast.ops.FitNoiseModel(
        noise_model=estim.out_model,
        out_model="fit_noise_model",
    )
    noise_fitter.apply(data)

    # MARK: Pointing Matrix

    det_point_azel = toast.ops.PointingDetectorSimple(
        boresight=defaults.boresight_azel,
        quats="quats_azel"
    )

    det_point_radec = toast.ops.PointingDetectorSimple(
        boresight=defaults.boresight_radec,
        quats="quats_radec"
    )

    nside = 256
    pixels_radec = toast.ops.PixelsHealpix(
        nside=nside,
        nest=True,
        detector_pointing=det_point_radec,
    )

    weights_azel = toast.ops.StokesWeights(
        mode="IQU",
        detector_pointing=det_point_azel,
    )

    weights_radec = toast.ops.StokesWeights(
        mode="IQU",
        detector_pointing=det_point_radec,
    )

    pix_dist = toast.ops.BuildPixelDistribution(
        pixel_dist="pixel_dist",
        pixel_pointing=pixels_radec,
    )

    # MARK: BINNING
    # Set up binning operator for solving
    binner = toast.ops.BinMap(
        pixel_dist=pix_dist.pixel_dist,
        pixel_pointing=pixels_radec,
        stokes_weights=weights_radec,
        noise_model=noise_fitter.out_model,
    )

    # The Offset template models 1/f noise as a stepwise function, which
    # is the same as a "classic" destriper.

    tmpl_offset = toast.templates.Offset(
        times=defaults.times,
        noise_model=noise_fitter.out_model,
        step_time=1.0 * u.second,
    )

    # Build a template matrix with our templates.

    tmatrix = toast.ops.TemplateMatrix(
        templates=[tmpl_offset],
    )

    # If the outdir doesn't exist, make it
    if not os.path.exists(out_dir):
        os.makedirs(out_dir)

    map_maker = toast.ops.MapMaker(
        name="mapmaker",
        binning=binner,
        template_matrix=tmatrix,
        solve_rcond_threshold=1.0e-1,
        map_rcond_threshold=1.0e-1,
        iter_min=200,
        iter_max=300,
        write_hits=True,
        write_map=True,
        write_binmap=True,
        write_cov=False,
        write_invcov=False,
        write_rcond=True,
        output_dir=out_dir,
        keep_solver_products=True, # We set this to True so we can plot solved template amplitudes later
    )
    map_maker.apply(data)

    plot_maps(
        root=out_dir,
        range_I=(-0.01, 0.01),
        range_Q=(-0.0002, 0.0002),
        range_U=(-0.0002, 0.0002),
        max_hits=1000,
        truth=None,  # You can specify a truth map file here if available
    )

    return